<a href="https://colab.research.google.com/github/yorkville101/3D-projection-tutorial/blob/main/fastai_0112.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
t= np.arange(12).reshape(3,4)
print(t)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
